services:
  db:
    image: mysql
    container_name: e-bake-ingredients-db
    volumes:
      - data:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "3306:3306"

  mail:
    image: maildev/maildev
    container_name: e-bake-ingredients-mail
    ports:
      - "1080:1080"
      - "1025:1025"

  web:
    build:
      context: .
    container_name: e-bake-ingredients-web
    env_file:
      - web.env
    ports:
      - "8080:8080"
volumes:
  data:
